version: "3.9" 
services:
  gomatalk:
    image: omatztw/gomatalk
    restart: always
    environment:
      TZ: Asia/Tokyo
    tmpfs: /tmp
    volumes:
      - ./wav:/workspace/wav
      - ./config.toml:/workspace/config/config.toml
      - ./data:/workspace/data
      - ./voices:/workspace/voices